# NOTE: Generated By HttpRunner v3.1.4
# FROM: meego_story_operate.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMeegoStoryOperate(HttpRunner):
    config = Config("testname").variables(**{
        "x-tt-env": "stress_test",
        "token": ""
    }).verify(False)

    teststeps = [
        Step(
            RunRequest("customize path")
                .post("url")
                .with_headers(
                **{
                    "header": "hedaer"
                }
            )
                .with_json(
                "json"
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
                .assert_equal("body.statusCode", 0)
                .assert_equal("body.errMsg", None)
        )
    ]


if __name__ == "__main__":
    TestCaseMeegoStoryOperate().test_start()
