# NOTE: Generated By HttpRunner v3.1.4
# FROM: meego_story_operate.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMeegoStoryOperate(HttpRunner):
    config = Config("testcase description").variables(**{
        "x-tt-env": "stress_test",
        "token": ""
    }).verify(False)

    teststeps = [
        Step(
            RunRequest("/api/story/604ebf5ad9e64d02a92a92fd")
                .post("https://meego.boe.bytedance.net/api/story/604ebf5ad9e64d02a92a92fd")
                .with_headers(
                **{
                    "Host": "meego.boe.bytedance.net",
                    "Connection": "keep-alive",
                    "Content-Length": "1746",
                    "Pragma": "no-cache",
                    "Cache-Control": "no-cache",
                    "Accept": "application/json, text/plain, */*",
                    "Authorization": "${token}",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Origin": "https://bits-boe.bytedance.net",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://bits-boe.bytedance.net/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "x-use-boe": "1",
                    "x-tt-env": "${x-tt-env}",
                }
            )
                .with_json(
                {
                    "business": "604ebf5ad9e64d02a92a92fe",
                    "name": "接口压力/性能测试",
                    "description": {
                        "doc": '{"initialAttributedText":{"text":"接口压力/性能测试\\n","attribs":"*1+9|1+1"},"initialAttributedTexts":{"rows":{},"cols":{},"text":{"0":"接口压力/性能测试\\n"},"attribs":{"0":"*1+9|1+1"}},"apool":{"numToAttrib":{"0":["author","0"],"1":["lineguid","OKrJHu"],"2":["lineguid","2uaJ3s"],"3":["lineguid","PRliWb"]},"nextNum":4},"style":{}}',
                        "doc_text": "接口压力/性能测试",
                        "doc_html": '<div id="magicdomid-1_3" class="ace-line locate lineguid-OKrJHu" dir="auto"><span>接口压力/性能测试</span></div>',
                        "is_empty": False,
                        "notify_user_list": [],
                    },
                    "wiki": "https://bytedance.feishu.cn/docs/doccnm80jA5c66hQdN6eQWmmhNe#tN4nc1",
                    "template_type": "stress_test_auto_generate__featuremanagement_auto_generate__empty_auto_generate",
                    "priority": 1,
                    "start_time": "2021-03-15T02:03:07.982Z",
                    "tags": ["测试", "开发"],
                    "watchers": [],
                    "for_leopard": {
                        "group_type": "disabled",
                        "field_4": "https://www.figma.com/file/zaxLnnQuREt9dgoS314wnD/Meego-Mobile?node-id=114%3A739",
                        "field_5": "https://bytedance.feishu.cn/docs/doccntOJv4QgSNwBWPDUjaZ7ysh#Mv3r87",
                    },
                    "sprints": [],
                    "role_owners": [
                        {"role": "PM", "owners": ["yanxuping@bytedance.com"]},
                        {"role": "RD", "owners": []},
                        {"role": "DA", "owners": []},
                        {"role": "UI", "owners": []},
                        {"role": "UE", "owners": []},
                        {"role": "UX_Writer", "owners": []},
                        {"role": "tech_owner", "owners": []},
                        {"role": "iOS", "owners": []},
                        {"role": "Android", "owners": []},
                        {"role": "Server", "owners": []},
                        {"role": "FE", "owners": []},
                        {"role": "Data", "owners": []},
                        {"role": "QA", "owners": []},
                        {
                            "role": "reporter213131231231",
                            "owners": ["yanxuping@bytedance.com"],
                        },
                    ],
                    "app_infos": [],
                    "related_epic": "",
                    "is_epic": False,
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
                .assert_equal("body.statusCode", 0)
                .assert_equal("body.errMsg", None)
        )
    ]


if __name__ == "__main__":
    TestCaseMeegoStoryOperate().test_start()
